### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/task-executor#1]
- [x] template store
  - [x] algorithm image name
  - [x] worker image name
  - [x] algorithm resource requirements
  - [x] allow to add env to worker and algorithm
- [x] delete pod when worker finishes
- [x] add metrics (job requests)
- [x] worker metrics problem
- [x] fix jaeger
